version: '3.1'
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5442:5432"
    environment:
      POSTGRES_PASSWORD: sspw
      POSTGRES_DB: dbcmp_test
      POSTGRES_USER: pguser
    healthcheck:
      test: [ "CMD", "pg_isready", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 3
  mysql:
    image: "mysql:8"
    restart: always
    ports:
      - "3316:3306"
    environment:
      MYSQL_DATABASE: dbcmp_test
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: sspw
      MYSQL_ROOT_PASSWORD: sspw
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 3
  mysql-legacy:
    image: "mysql:5.7"
    restart: always
    ports:
      - "3326:3306"
    environment:
      MYSQL_DATABASE: dbcmp_test
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: sspw
      MYSQL_ROOT_PASSWORD: sspw
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 3
